Al 31 liste theme
AlgoTeamOrg/AlgoflexPublic pull request #20
Opened 2022-03-02 14:41 UTC by AlexisBarth

Themes et exercices mis à jour et lié à l'API (live sur heroku).

Authentification non prise en compte.

2022-03-03 09:09 UTC, Hugo087 requested changes

2022-03-03 09:09 UTC, Hugo087 commented on algoflex_frontend/src/components/CardItem/CardItem.tsx
> +        let url = "/theme/"+props.uid;
NIT : Hésite pas à mettre des espaces au tour de ton "+"

2022-03-03 09:09 UTC, Hugo087 commented on algoflex_frontend/src/components/interfaces.ts
> +import { integer } from "@codingame/monaco-languageclient";
Pourquoi tu as besoin de cet import ?

2022-03-03 09:09 UTC, Hugo087 commented on algoflex_frontend/src/views/Exercices/components/Exercices.tsx
> +import {useEffect} from "react";
NIT : Pareil tu peux espacer un peu au tour de ton "useEffect"

2022-03-03 09:09 UTC, Hugo087 commented on algoflex_frontend/src/views/Exercices/components/Exercices.tsx
> +    axios.get('https://staging-algoflex.herokuapp.com/problems/coding-questions?theme='+idPage.id,  { withCredentials: false})
Faudrait éviter ça, soit tu fait un alias global, soit faut que tu regardes si dans axios tu peux mettre une adresse par défaut (Vu qu'a priori on en aura qu'une seule)

2022-03-03 09:09 UTC, Hugo087 commented on algoflex_frontend/src/views/Themes/components/Themes.tsx
> +    }, [])
Si tu met des ";", il faut en mettre partout.

2022-03-03 09:09 UTC, Hugo087 commented on algoflex_frontend/src/views/Exercices/components/Exercices.tsx
> +  }, [idPage.id])
Ici aussi, il manque des ;

2022-03-03 09:16 UTC, Hugo087 commented on algoflex_frontend/src/components/CardItem/CardItem.tsx
>  export default function CardItem(props: CardItemProps) {
C'est dommage il n'y a pas de tests unitaires

2022-03-03 13:17 UTC, Hugo087 commented
Il faudrait des screen shots je pense

2022-03-04 09:34 UTC, AlexisBarth commented on algoflex_frontend/src/components/interfaces.ts
> +import { integer } from "@codingame/monaco-languageclient";
done

2022-03-04 09:34 UTC, AlexisBarth commented on algoflex_frontend/src/views/Exercices/components/Exercices.tsx
> +import {useEffect} from "react";
done

2022-03-04 09:50 UTC, AlexisBarth commented on algoflex_frontend/src/views/Exercices/components/Exercices.tsx
> +    axios.get('https://staging-algoflex.herokuapp.com/problems/coding-questions?theme='+idPage.id,  { withCredentials: false})
done créé global.ts avec basUrl pour les requêtes API

2022-03-04 09:51 UTC, AlexisBarth commented on algoflex_frontend/src/views/Themes/components/Themes.tsx
> +    }, [])
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

2022-03-04 09:51 UTC, AlexisBarth commented on algoflex_frontend/src/views/Exercices/components/Exercices.tsx
> +  }, [idPage.id])
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

2022-03-04 09:52 UTC, AlexisBarth commented on algoflex_frontend/src/components/CardItem/CardItem.tsx
>  export default function CardItem(props: CardItemProps) {
Patience mon petit

2022-03-04 09:57 UTC, AlexisBarth commented
Le code smell est skipable pour le moment je pense..

2022-03-04 13:12 UTC, AlexisBarth commented
Supression global.ts, mise à jour du service axios avec url base d'heroku.
Attention à ceux qui tournent en local

2022-03-04 15:57 UTC, AlexisBarth commented
![image](https://user-images.githubusercontent.com/73121364/156796413-a480a324-db60-4ce0-a50c-79316cbc971a.png)

![image](https://user-images.githubusercontent.com/73121364/156796506-19189355-93c2-42c6-a139-fa5bbe8b0dc1.png)

2022-03-31 12:16 UTC, Hugo087 approved these changes

2022-03-31 12:16 UTC, merged